config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'angular-items', to: 'portfolios#angular'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
    enum status: {draft: 0, published: 1}
    extend FriendlyId
    friendly_id :title, use: :slugged

    validates_presence_of :title, :body, :topic_id

    belongs_to :topic, optional: true

    has_many :comments, dependent: :destroy

    scope :sort_by_recent, -> { order("created_at DESC") }
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_side_bar_topics, except: [:destroy, :create, :update, :toggle_status]
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all
  
  # GET /blogs
  # GET /blogs.json
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.sort_by_recent.page(params[:page]).per(5)
    else
      @blogs = Blog.sort_by_recent.published.page(params[:page]).per(5)
    end
    set_title("My Blog")
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new
      
      set_title(@blog.title)
      set_seo_keywords(@blog.title) 
    else
      redirect_to blogs_path, notice: "You are not authorised to access this page"
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published! if @blog.draft?
    elsif @blog.published?
      @blog.draft! if @blog.published?
    end
    redirect_to blogs_url, notice: 'Status has been updated'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end

    def set_side_bar_topics
      @side_bar_topics = Topic.with_blogs
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
    def gravatar_helper user
        image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
    end

    class CodeRayify < Redcarpet::Render::HTML
        def block_code(code, language)
            CodeRay.scan(code, language).div
        end
    end

    def markdown(text)
        coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

        options = {
            fenced_code_blocks: true,
            no_intra_emphasis: true,
            autolink: true,
            lax_html_blocks: true
        }

        markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
        markdown_to_html.render(text).html_safe
    end

    def blog_status_color blog
        'color: red;' if blog.draft?
    end
end

app/views/blogs/_admin_actions.html.erb
    <% if logged_in?(:site_admin) %>
    <p class="breadcrumb blogcrumb">
        <%= link_to fa_icon('file-text'), toggle_status_blog_path(blog), style: blog_status_color(blog) %>
        <%= link_to fa_icon('pencil-square-o'), edit_blog_path(blog) %>
        <%= link_to fa_icon('trash'), blog, method: :delete, data: { confirm: 'Are you sure?' } %> 
    </p>
    <% end %>

app/views/blogs/_blog.html.erb
<div class="blog-post">
    <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
    <p class="blog-post-meta"><%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>
    
    <%= render partial: 'blogs/admin_actions', locals: { blog: blog } %>
   
    <p>
        <%= blog.body %>
    </p>

</div><!-- /.blog-post -->

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, id: :blog_title, class: 'form-control', placeholder: 'Title' %>
  </div>

  <div class="form-group">
    <%= form.label :topic_id %>
    <%= form.collection_select(:topic_id, Topic.all, :id, :title,
                              {
                                include_blank: true
                              },
                              class: 'form-control'
                              )
    %>
  </div>

  <div class="form-group">
    <%= form.radio_button :status, 'draft' %>
    <%= form.label :status, 'Draft' %>

    <%= form.radio_button :status, 'published' %>
    <%= form.label :status, 'Published' %>
  </div>

  <div class="form-group">
    <%= form.text_area :body, id: :blog_body, rows: '15', class: 'form-control', placeholder: 'Content' %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">

    <h1>Editing Blog</h1>

    <%= render 'form', blog: @blog %>

    <%= link_to 'Show', @blog %> |
    <%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">

  <%= paginate @blogs %>
  
  <%= render @blogs%>

  <%= paginate @blogs %>

</div>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">

    <h1>New Blog</h1>

    <%= render 'form', blog: @blog %>

    <%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">

  <h2><%= @blog.title %></h2>

  <nav class="breadcrumb">
    <%= link_to "Home", root_path, class: "breadcrumb-item" %>
    <%= link_to @blog.topic.title, topic_path(@blog.topic), class: "breadcrumb-item" %>
    <span class="breadcrumb-item active"><%= @blog.title %></span>

    <span class="ml-auto">
      <%= link_to fa_icon('pencil-square-o'), edit_blog_path(@blog) if logged_in?(:site_admin) %>
      <%= link_to fa_icon('trash'), @blog, method: :delete, 
            data: { confirm: 'Are you sure you want to delete this post?'} if logged_in?(:site_admin) %>
    </span>
  </nav>

  <p><%= @blog.topic.title %></p>

  <p>
    <%= markdown @blog.body %>
  </p>

  <%= render 'comments/comment_form' %>

  <div id="comments" data-blog-id="<%= @blog.id %>">
    <%= render @blog.comments %>
  </div>
</div>