config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'angular-items', to: 'portfolios#angular'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies, 
                                  allow_destroy: true,
                                  reject_if: lambda { |attrs| attrs['name'].blank? }

    validates_presence_of :title

    mount_uploader :thumb_image, PortfolioUploader
    mount_uploader :main_image, PortfolioUploader

    scope :sorted_by_display_position, -> { order("position ASC") }

    scope :with_subtitle_ruby_on_rails, -> { where(subtitle: "Ruby on Rails")}
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
    layout "portfolio"
    access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

    def index
        @portfolio_items = Portfolio.sorted_by_display_position
    end

    def sort
        params[:order].each do |key, value|
            Portfolio.find(value[:id]).update(position: value[:position])
        end

        render body: nil
    end

    def new
        @portfolio_item = Portfolio.new
    end

    def create
        @portfolio_item = Portfolio.new(portfolio_params)
        
        respond_to do |format|
            if @portfolio_item.save
                format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully created.' }
            else
                format.html { render :new }
            end
        end
    end

    def edit
    end

    def update
        respond_to do |format|
          if @portfolio_item.update(portfolio_params)
            format.html { redirect_to portfolios_path, 
                notice: 'Portfolio item was successfully updated.' }
          else
            format.html { render :edit }
          end
        end
    end

    def show
    end

    def destroy
        @portfolio_item.destroy
        
        respond_to do |format|
          format.html { redirect_to portfolios_url, 
            notice: 'Portfolio item was successfully destroyed.' }
        end
    end

    private

    def portfolio_params
        params.require(:portfolio).permit(:title, 
                                          :subtitle, 
                                          :body, 
                                          :main_image,
                                          :thumb_image,
                                          technologies_attributes: [:id, :name, :_destroy]
                                          )
    end

    def set_portfolio_item
        @portfolio_item = Portfolio.find(params[:id])
    end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
    def image_generator(height:, width:)
        "http://via.placeholder.com/#{height}x#{width}"
    end

    def portfolio_img img, type
        if img.model.main_image? || img.model.thumb_image?
            img
        elsif type == 'thumb'
            image_generator(height: '350', width: '200')
        elsif type == 'main'
            image_generator(height: '600', width: '400')
        end
    end
end

        

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>

  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: 'form-control' %>
      </div>   

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file <%= form.file_field :main_image, style: 'display:none' %>
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file <%= form.file_field :thumb_image, style: 'display:none' %>
        </label>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows: 12 %>
      </div>    
    </div>
  </div>


  <hr>
  
  <div class="col-md-12">
    <h2>Technologies Used:</h2>
    <div>
      <%= form.fields_for :technologies do |technologies_form| %>
        <%= render 'technology_fields', f: technologies_form %>
      <% end %>

      <div>
        <%= link_to_add_association 'Add Technology', form, :technologies %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">  
      <div class="actions" class="form-group">
        <%= form.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="actions" class="form-group">
      <% if @portfolio_item.id? %>
        <%= link_to 'Cancel', portfolio_path(@portfolio_item), class: 'btn btn-warning btn-block' %>
      <% else %>
        <%= link_to 'Cancel', portfolios_path, class: 'btn btn-warning btn-block' %>
      <% end %%>
      </div>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
    <div class="card" data-id="<%= portfolio_item.id %>">
        <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb'), width: '100%' %>
        <p class="card-text">
            <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %> <%= portfolio_item.subtitle %></span>
        </p>
    </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

<% @angular_portfolio_items. each do |portfolio_item| %>
    <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
    <p><%= portfolio_item.subtitle %></p>
    <p><%= portfolio_item.body %></p>
    <p><%= portfolio_item.main_image %></p>
    <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
    <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
    <%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
    <h1>Edit this Portfolio item</h1>

    <%= render 'form', portfolio_item: @portfolio_item%>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
    <div class="container">
        <%= source_helper("alert alert-primary") %>
        
        <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
            <%= render partial: 'portfolio_item', collection: @portfolio_items %>
        </div>
    </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
    <h1>Create a new Portfolio item</h1>

    <%= render 'form', portfolio_item: @portfolio_item%>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
    <div class="row">
        <div class="col-md-7">
            <%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '100%'%>  
        </div>

        <div class="col-md-5">
            <h1><%= @portfolio_item.title %></h1>

            <hr>

            <em><%= @portfolio_item.subtitle %></em>

            <p><%= @portfolio_item.body%>

            <hr>

            <h3>Technologies Used: </h3>

            <% @portfolio_item.technologies.each do |t| %>
                <p><%= t.name %></p>
            <% end %>  

            <% if logged_in?(:site_admin) %>
                <div>
                    <%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class: 'btn btn-warning'%>
                </div>
            <% end %>
        </div>
    </div>
</div>